/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['IBM Plex Sans', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['IBM Plex Mono', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
      },
    },
  },
  plugins: [require("@tailwindcss/typography"), require("daisyui")],
  daisyui: {
    themes: [
      {
        industrial_light: {
          "primary": "#6D28D9",
          "primary-content": "#FAF9F5",
          "secondary": "#6E6A5F",
          "secondary-content": "#FAF9F5",
          "accent": "#6D28D9",
          "accent-content": "#FAF9F5",
          "neutral": "#262520",
          "neutral-content": "#F1EFE8",
          "base-100": "#FAF9F5",
          "base-200": "#F1EFE8",
          "base-300": "#E3E0D6",
          "base-content": "#1C1B17",
          "info": "#3b82f6",
          "info-content": "#ffffff",
          "success": "#22c55e",
          "success-content": "#ffffff",
          "warning": "#f59e0b",
          "warning-content": "#ffffff",
          "error": "#ef4444",
          "error-content": "#ffffff",
          "--rounded-box": "0.375rem",
          "--rounded-btn": "0.25rem",
          "--rounded-badge": "0.125rem",
          "--animation-btn": "0",
          "--btn-focus-scale": "1",
        },
      },
      {
        industrial_dark: {
          "primary": "#A78BFA",
          "primary-content": "#1A1523",
          "secondary": "#9B968B",
          "secondary-content": "#1A1918",
          "accent": "#A78BFA",
          "accent-content": "#1A1523",
          "neutral": "#2C2A27",
          "neutral-content": "#ECE9E2",
          "base-100": "#1A1918",
          "base-200": "#211F1D",
          "base-300": "#2C2A27",
          "base-content": "#ECE9E2",
          "info": "#3b82f6",
          "info-content": "#ffffff",
          "success": "#22c55e",
          "success-content": "#ffffff",
          "warning": "#f59e0b",
          "warning-content": "#ffffff",
          "error": "#ef4444",
          "error-content": "#ffffff",
          "--rounded-box": "0.375rem",
          "--rounded-btn": "0.25rem",
          "--rounded-badge": "0.125rem",
          "--animation-btn": "0",
          "--btn-focus-scale": "1",
        },
      },
    ],
    logs: false,
  }
}
